plugins {
    id "org.jetbrains.kotlin.jvm" version "2.0.20"
}

group 'com.koupper.cli'
version '7.1.1'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-script-runtime:2.0.20"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0'
    implementation 'org.yaml:snakeyaml:2.2'
    implementation 'com.fasterxml.jackson.module:jackson-module-kotlin:2.17.0'

    testImplementation "org.jetbrains.kotlin:kotlin-test:2.0.20"
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit5:2.0.20"
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes 'Main-Class': 'com.koupper.cli.CommandManagerKt'
        attributes 'Implementation-Title': 'Koupper CLI'
        attributes 'Implementation-Version': project.version
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from {
        configurations.runtimeClasspath.collect { dep ->
            dep.isDirectory() ? dep : zipTree(dep).matching {
                exclude 'module-info.class'
                exclude 'META-INF/versions/*/module-info.class'
                exclude 'META-INF/services/javax.annotation.processing.Processor'
                exclude 'META-INF/*.SF'
                exclude 'META-INF/*.DSA'
                exclude 'META-INF/*.RSA'
            }
        }
    }
}
